modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="dynasty"
version="0.1.0"
displayName="Dynasty"
logoFile="dynasty.png"
credits=""
authors="Mr. Pineapple, Serenity"
description=""

[[dependencies.dynasty]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynasty]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
